openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /pages:
    get:
      operationId: loadPages
      responses:
        '200':
          description: List of pages
          content:
            'application/json':
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PageListItem'
                  links:
                    $ref: '#/components/schemas/PaginationLinks'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'

components:
  schemas:
    PaginationLinks:
      type: object
      properties:
        first:
          type: string
          format: url
        last:
          type: string
          format: url
        prev:
          type: string
          format: url
          nullable: true
        next:
          type: string
          format: url
          nullable: true
    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
        from:
          type: integer
        last_page:
          type: integer
        links:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                format: url
              label:
                type: string
              active:
                type: boolean
        path:
          type: string
          format: url
        per_page:
          type: integer
        to:
          type: integer
        total:
          type: integer
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Meta:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        og_type:
          type: string
        class_name:
          type: string
          default: 'meta'
        attachment:
          $ref: '#/components/schemas/Attachment'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Attachment:
      type: object
      properties:
        id:
          type: integer
        file:
          $ref: '#/components/schemas/File'
        role:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      nullable: true
    File:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - 'image'
            - 'video'
            - 'file'
        path:
          type: string
          format: url
        disk:
          type: string
        mime:
          type: string
        original_name:
          type: string
        size:
          type: number
        user:
          $ref: '#/components/schemas/User'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    PageListItem:
      type: object
      properties:
        id:
          type: integer
        slug:
          type: string
        title:
          type: string
        active:
          type: boolean
        user:
          $ref: '#/components/schemas/User'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Page:
      type: object
      properties:
        id:
          type: integer
        slug:
          type: string
        title:
          type: string
        active:
          type: boolean
        user:
          $ref: '#/components/schemas/User'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        class_name:
          type: string
          default: 'page'
        blocks:
          type: array
        meta:
          $ref: '#/components/schemas/Meta'

